2020-07-20 18:33:57 - root - INFO - Connection with MYSQL ready
2020-07-20 18:33:57 - root - INFO - Database was created successfully
2020-07-20 18:33:59 - root - INFO - Tables were created successfully
2020-07-20 18:35:06 - root - INFO - Browser connect to URL
2020-07-20 18:35:06 - root - INFO - Search for job title
2020-07-20 18:35:06 - root - INFO - Search for job location
2020-07-20 18:35:15 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:35:21 - root - INFO - Browser connect to new URL
2020-07-20 18:35:37 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:35:37 - root - INFO - Succeed to catch number of available pages
2020-07-20 18:35:48 - root - INFO - Succeed to close popup'
2020-07-20 18:35:48 - root - INFO - Start to collect all data from page
2020-07-20 18:36:15 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:36:15 - root - INFO - Insert company to DB successfully
2020-07-20 18:36:15 - root - INFO - Insert job to DB successfully
2020-07-20 18:36:41 - root - INFO - Insert company to DB successfully
2020-07-20 18:36:41 - root - INFO - Get information from DB
2020-07-20 18:36:41 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:36:41 - root - INFO - Get information from DB
2020-07-20 18:36:41 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:36:41 - root - INFO - Get information from DB
2020-07-20 18:36:41 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:36:41 - root - INFO - Insert job to DB successfully
2020-07-20 18:37:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:37:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:37:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:37:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:37:07 - root - INFO - Insert company to DB successfully
2020-07-20 18:37:07 - root - INFO - Insert job to DB successfully
2020-07-20 18:37:33 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:37:33 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:37:33 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:37:34 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:37:34 - root - INFO - Insert company to DB successfully
2020-07-20 18:37:34 - root - INFO - Insert job to DB successfully
2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Size"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Type"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Revenue"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Headquarters"]//following-sibling::*

2020-07-20 18:37:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:37:59 - root - INFO - Insert company to DB successfully
2020-07-20 18:37:59 - root - INFO - Insert job to DB successfully
2020-07-20 18:38:26 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:38:26 - root - INFO - Insert company to DB successfully
2020-07-20 18:38:26 - root - INFO - Insert job to DB successfully
2020-07-20 18:38:52 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:38:52 - root - INFO - Insert company to DB successfully
2020-07-20 18:38:52 - root - INFO - Insert job to DB successfully
2020-07-20 18:39:18 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:39:18 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:39:18 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:39:18 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:39:18 - root - INFO - Insert company to DB successfully
2020-07-20 18:39:18 - root - INFO - Insert job to DB successfully
2020-07-20 18:39:44 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:39:44 - root - INFO - Insert company to DB successfully
2020-07-20 18:39:44 - root - INFO - Insert job to DB successfully
2020-07-20 18:40:13 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:40:13 - root - INFO - Insert company to DB successfully
2020-07-20 18:40:13 - root - INFO - Insert job to DB successfully
2020-07-20 18:40:40 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:40:40 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:40:40 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:40:40 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:40:40 - root - INFO - Insert company to DB successfully
2020-07-20 18:40:40 - root - INFO - Insert job to DB successfully
2020-07-20 18:41:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:41:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:41:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:41:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:41:05 - root - INFO - Insert company to DB successfully
2020-07-20 18:41:05 - root - INFO - Insert job to DB successfully
2020-07-20 18:41:31 - root - INFO - Insert company to DB successfully
2020-07-20 18:41:31 - root - INFO - Get information from DB
2020-07-20 18:41:31 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:41:31 - root - INFO - Get information from DB
2020-07-20 18:41:31 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:41:31 - root - INFO - Get information from DB
2020-07-20 18:41:31 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:41:31 - root - INFO - Insert job to DB successfully
2020-07-20 18:41:58 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:41:58 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:41:58 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:41:58 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:41:58 - root - INFO - Insert company to DB successfully
2020-07-20 18:41:58 - root - INFO - Insert job to DB successfully
2020-07-20 18:42:24 - root - INFO - Insert company to DB successfully
2020-07-20 18:42:24 - root - INFO - Get information from DB
2020-07-20 18:42:42 - root - INFO - Browser connect to URL
2020-07-20 18:42:43 - root - INFO - Search for competitor's company page
2020-07-20 18:42:43 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:42:54 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:43:14 - root - INFO - Close browser successfully
2020-07-20 18:43:14 - root - INFO - Insert company to DB successfully
2020-07-20 18:43:14 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:43:14 - root - INFO - Get information from DB
2020-07-20 18:43:31 - root - INFO - Browser connect to URL
2020-07-20 18:43:32 - root - INFO - Search for competitor's company page
2020-07-20 18:43:32 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:43:45 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:44:02 - root - INFO - Close browser successfully
2020-07-20 18:44:02 - root - INFO - Insert company to DB successfully
2020-07-20 18:44:02 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:44:02 - root - INFO - Get information from DB
2020-07-20 18:44:16 - root - INFO - Browser connect to URL
2020-07-20 18:44:17 - root - INFO - Search for competitor's company page
2020-07-20 18:44:17 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:44:25 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:44:44 - root - INFO - Close browser successfully
2020-07-20 18:44:44 - root - INFO - Insert company to DB successfully
2020-07-20 18:44:44 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:44:44 - root - INFO - Insert job to DB successfully
2020-07-20 18:45:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:45:10 - root - INFO - Insert company to DB successfully
2020-07-20 18:45:10 - root - INFO - Insert job to DB successfully
2020-07-20 18:45:37 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:45:37 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:45:37 - root - INFO - Insert company to DB successfully
2020-07-20 18:45:37 - root - INFO - Insert job to DB successfully
2020-07-20 18:46:03 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:46:03 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:46:03 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:46:03 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:46:03 - root - INFO - Insert company to DB successfully
2020-07-20 18:46:03 - root - INFO - Insert job to DB successfully
2020-07-20 18:46:29 - root - INFO - Insert company to DB successfully
2020-07-20 18:46:29 - root - INFO - Get information from DB
2020-07-20 18:46:29 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:46:29 - root - INFO - Get information from DB
2020-07-20 18:46:29 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:46:29 - root - INFO - Insert job to DB successfully
2020-07-20 18:46:55 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:46:55 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:46:55 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:46:55 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:46:55 - root - INFO - Insert company to DB successfully
2020-07-20 18:46:55 - root - INFO - Insert job to DB successfully
2020-07-20 18:47:21 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:47:21 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:47:21 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:47:21 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:47:21 - root - INFO - Insert company to DB successfully
2020-07-20 18:47:21 - root - INFO - Insert job to DB successfully
2020-07-20 18:47:48 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:47:48 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:47:48 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:47:48 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:47:48 - root - INFO - Insert company to DB successfully
2020-07-20 18:47:48 - root - INFO - Insert job to DB successfully
2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Size"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Type"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Revenue"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Headquarters"]//following-sibling::*

2020-07-20 18:48:14 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:48:14 - root - INFO - Insert company to DB successfully
2020-07-20 18:48:14 - root - INFO - Insert job to DB successfully
2020-07-20 18:48:41 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:48:41 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:48:41 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:48:41 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:48:41 - root - INFO - Insert company to DB successfully
2020-07-20 18:48:41 - root - INFO - Insert job to DB successfully
2020-07-20 18:49:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:49:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:49:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:49:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:49:07 - root - INFO - Insert company to DB successfully
2020-07-20 18:49:07 - root - INFO - Insert job to DB successfully
2020-07-20 18:49:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:49:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:49:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:49:33 - root - INFO - Insert company to DB successfully
2020-07-20 18:49:33 - root - INFO - Insert job to DB successfully
2020-07-20 18:49:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:49:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:49:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:49:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:49:59 - root - INFO - Insert company to DB successfully
2020-07-20 18:49:59 - root - INFO - Insert job to DB successfully
2020-07-20 18:50:25 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:50:25 - root - INFO - Insert company to DB successfully
2020-07-20 18:50:25 - root - INFO - Insert job to DB successfully
2020-07-20 18:50:51 - root - INFO - Insert company to DB successfully
2020-07-20 18:50:51 - root - INFO - Get information from DB
2020-07-20 18:51:04 - root - INFO - Browser connect to URL
2020-07-20 18:51:06 - root - INFO - Search for competitor's company page
2020-07-20 18:51:06 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:51:14 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:51:33 - root - INFO - Close browser successfully
2020-07-20 18:51:33 - root - INFO - Insert company to DB successfully
2020-07-20 18:51:33 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:51:33 - root - INFO - Get information from DB
2020-07-20 18:51:44 - root - INFO - Browser connect to URL
2020-07-20 18:51:45 - root - INFO - Search for competitor's company page
2020-07-20 18:51:45 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:51:53 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:52:13 - root - INFO - Close browser successfully
2020-07-20 18:52:13 - root - INFO - Insert company to DB successfully
2020-07-20 18:52:13 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:52:13 - root - INFO - Get information from DB
2020-07-20 18:52:23 - root - INFO - Browser connect to URL
2020-07-20 18:52:27 - root - INFO - Search for competitor's company page
2020-07-20 18:52:27 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:52:33 - root - INFO - Browser connect to new URL of a company
2020-07-20 18:52:53 - root - INFO - Close browser successfully
2020-07-20 18:52:53 - root - INFO - Insert company to DB successfully
2020-07-20 18:52:53 - root - INFO - Insert competitors to DB successfully
2020-07-20 18:52:53 - root - INFO - Insert job to DB successfully
2020-07-20 18:53:19 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:53:19 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:53:19 - root - INFO - Insert company to DB successfully
2020-07-20 18:53:19 - root - INFO - Insert job to DB successfully
2020-07-20 18:53:47 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:53:47 - root - INFO - Insert company to DB successfully
2020-07-20 18:53:47 - root - INFO - Insert job to DB successfully
2020-07-20 18:54:04 - root - ERROR - There is a problem with catch mandatory data
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/jobs_list_scraping.py", line 143, in catch_mandatory_data_and_rating
    job_description = self.browser.find_element_by_xpath(self.config['Path']['JOB_DESCRIPTION_XPATH']).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="jobDescriptionContent desc"]

2020-07-20 18:54:21 - root - ERROR - There is a problem with catch mandatory data
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/jobs_list_scraping.py", line 134, in catch_mandatory_data_and_rating
    self.config['Path']['COMPANY_NAME_XPATH']).text)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="employerName"]

2020-07-20 18:54:37 - root - ERROR - There is a problem with catch mandatory data
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/jobs_list_scraping.py", line 134, in catch_mandatory_data_and_rating
    self.config['Path']['COMPANY_NAME_XPATH']).text)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="employerName"]

2020-07-20 18:55:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:55:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:55:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:55:05 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:55:05 - root - INFO - Insert company to DB successfully
2020-07-20 18:55:05 - root - INFO - Insert job to DB successfully
2020-07-20 18:55:05 - root - INFO - Succeed to collect all data from page
2020-07-20 18:55:06 - root - INFO - Succeed to click on next button for next page
2020-07-20 18:55:14 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 29, in close_popup
    pop_up = self.browser.find_element_by_xpath(self.config['Path']['POP_UP_XPATH'])
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 18:55:14 - root - INFO - Start to collect all data from page
2020-07-20 18:55:40 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:55:40 - root - INFO - Insert company to DB successfully
2020-07-20 18:55:40 - root - INFO - Insert job to DB successfully
2020-07-20 18:56:07 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:56:07 - root - INFO - Insert company to DB successfully
2020-07-20 18:56:07 - root - INFO - Insert job to DB successfully
2020-07-20 18:56:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:56:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:56:32 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:56:33 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:56:33 - root - INFO - Insert company to DB successfully
2020-07-20 18:56:33 - root - INFO - Insert job to DB successfully
2020-07-20 18:56:59 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:56:59 - root - INFO - Insert company to DB successfully
2020-07-20 18:56:59 - root - INFO - Insert job to DB successfully
2020-07-20 18:57:25 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:57:25 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:57:25 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:57:25 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:57:25 - root - INFO - Insert company to DB successfully
2020-07-20 18:57:25 - root - INFO - Insert job to DB successfully
2020-07-20 18:57:52 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:57:52 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:57:52 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:57:52 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:57:52 - root - INFO - Insert company to DB successfully
2020-07-20 18:57:52 - root - INFO - Insert job to DB successfully
2020-07-20 18:58:17 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:58:17 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:58:17 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:58:17 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:58:17 - root - INFO - Insert company to DB successfully
2020-07-20 18:58:17 - root - INFO - Insert job to DB successfully
2020-07-20 18:58:44 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:58:44 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:58:44 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:58:44 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:58:44 - root - INFO - Insert company to DB successfully
2020-07-20 18:58:44 - root - INFO - Insert job to DB successfully
2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Size"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Type"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Revenue"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Headquarters"]//following-sibling::*

2020-07-20 18:59:10 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:59:10 - root - INFO - Insert company to DB successfully
2020-07-20 18:59:10 - root - INFO - Insert job to DB successfully
2020-07-20 18:59:36 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Founded"]//following-sibling::*

2020-07-20 18:59:36 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Industry"]//following-sibling::*

2020-07-20 18:59:36 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Sector"]//following-sibling::*

2020-07-20 18:59:36 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 18:59:36 - root - INFO - Insert company to DB successfully
2020-07-20 18:59:36 - root - INFO - Insert job to DB successfully
2020-07-20 19:00:03 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 19:00:03 - root - INFO - Insert company to DB successfully
2020-07-20 19:00:03 - root - INFO - Insert job to DB successfully
2020-07-20 19:00:30 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 19:00:30 - root - INFO - Insert company to DB successfully
2020-07-20 19:00:30 - root - INFO - Insert job to DB successfully
2020-07-20 19:00:56 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 19:00:56 - root - INFO - Insert company to DB successfully
2020-07-20 19:00:56 - root - INFO - Insert job to DB successfully
2020-07-20 19:01:23 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 43, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 19:01:23 - root - INFO - Insert company to DB successfully
2020-07-20 19:01:23 - root - INFO - Insert job to DB successfully
